server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/druginventorymanagement?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
